/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResourceStateRouteImport } from './routes/resource-state'
import { Route as ResourceRadarRouteImport } from './routes/resource-radar'
import { Route as NegotiationsRouteImport } from './routes/negotiations'
import { Route as IndexRouteImport } from './routes/index'

const ResourceStateRoute = ResourceStateRouteImport.update({
  id: '/resource-state',
  path: '/resource-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceRadarRoute = ResourceRadarRouteImport.update({
  id: '/resource-radar',
  path: '/resource-radar',
  getParentRoute: () => rootRouteImport,
} as any)
const NegotiationsRoute = NegotiationsRouteImport.update({
  id: '/negotiations',
  path: '/negotiations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/negotiations': typeof NegotiationsRoute
  '/resource-radar': typeof ResourceRadarRoute
  '/resource-state': typeof ResourceStateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/negotiations': typeof NegotiationsRoute
  '/resource-radar': typeof ResourceRadarRoute
  '/resource-state': typeof ResourceStateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/negotiations': typeof NegotiationsRoute
  '/resource-radar': typeof ResourceRadarRoute
  '/resource-state': typeof ResourceStateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/negotiations' | '/resource-radar' | '/resource-state'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/negotiations' | '/resource-radar' | '/resource-state'
  id: '__root__' | '/' | '/negotiations' | '/resource-radar' | '/resource-state'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NegotiationsRoute: typeof NegotiationsRoute
  ResourceRadarRoute: typeof ResourceRadarRoute
  ResourceStateRoute: typeof ResourceStateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resource-state': {
      id: '/resource-state'
      path: '/resource-state'
      fullPath: '/resource-state'
      preLoaderRoute: typeof ResourceStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource-radar': {
      id: '/resource-radar'
      path: '/resource-radar'
      fullPath: '/resource-radar'
      preLoaderRoute: typeof ResourceRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negotiations': {
      id: '/negotiations'
      path: '/negotiations'
      fullPath: '/negotiations'
      preLoaderRoute: typeof NegotiationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NegotiationsRoute: NegotiationsRoute,
  ResourceRadarRoute: ResourceRadarRoute,
  ResourceStateRoute: ResourceStateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
